name: Wordpress Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: actions/setup-ssh@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          host-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Digital Ocean
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd ${{ secrets.DEPLOY_PATH }}
            git pull origin main
            sudo systemctl restart nginx
          EOF

